CREATE TABLE TIENDA (
    NIT NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    ESTADO VARCHAR2(10),
    CALIFICACION NUMBER(5,2),
    CERTIFICADA NUMBER(1)
);

CREATE TABLE CELULAR (
    IMEI NUMBER PRIMARY KEY,
    MODELO VARCHAR2(20),
    PRECIO NUMBER(10,2),
    TIENE5G NUMBER(1),
    ESTADO VARCHAR2(10),
    NIT NUMBER,
    CONSTRAINT FK_CEL_TIENDA FOREIGN KEY (NIT) REFERENCES TIENDA(NIT)
);