/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectocelular.gui;

import com.mycompany.proyectocelular.modelo.ClaseA;
import com.mycompany.proyectocelular.servicio.ServicioClaseA;

/**
 *
 * @author David Mahecha
 */
public class GUIActualizarCelular extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIActualizarCelular.class.getName());

    /**
     * Creates new form GUIActualizarCelular
     */
    public GUIActualizarCelular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImeiActualizar = new javax.swing.JLabel();
        txtImeiActualizar = new javax.swing.JTextField();
        lblModeloActualizar = new javax.swing.JLabel();
        txtModeloActualizar = new javax.swing.JTextField();
        lblPrecioActualizar = new javax.swing.JLabel();
        lblTiene5GActualizar = new javax.swing.JLabel();
        lblEstadoActualizar = new javax.swing.JLabel();
        txtPrecioActualizar = new javax.swing.JTextField();
        cmbActualizar = new javax.swing.JComboBox<>();
        chk5gActualizar = new javax.swing.JCheckBox();
        btnActualizar = new javax.swing.JButton();
        btnBuscarActualizar = new javax.swing.JButton();
        txtNitActualizar = new javax.swing.JTextField();
        lblNitActualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ActualizarCelular");

        lblImeiActualizar.setText("IMEI:");

        lblModeloActualizar.setText("Modelo:");

        lblPrecioActualizar.setText("Precio:");

        lblTiene5GActualizar.setText("Tiene 5G:");

        lblEstadoActualizar.setText("Estado: ");

        cmbActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBuscarActualizar.setText("BUSCAR");
        btnBuscarActualizar.addActionListener(this::btnBuscarActualizarActionPerformed);

        lblNitActualizar.setText("NIT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNitActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNitActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioActualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTiene5GActualizar)
                                    .addComponent(lblModeloActualizar)
                                    .addComponent(lblImeiActualizar)
                                    .addComponent(lblEstadoActualizar))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chk5gActualizar)
                                    .addComponent(txtImeiActualizar)
                                    .addComponent(txtModeloActualizar)
                                    .addComponent(txtPrecioActualizar)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(btnActualizar)
                                        .addGap(22, 22, 22)))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImeiActualizar)
                    .addComponent(txtImeiActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloActualizar)
                    .addComponent(txtModeloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioActualizar)
                    .addComponent(txtPrecioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiene5GActualizar)
                    .addComponent(chk5gActualizar))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNitActualizar)
                    .addComponent(txtNitActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBuscarActualizar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      int imei = Integer.parseInt(txtImeiActualizar.getText().trim());
      String modelo = txtModeloActualizar.getText().trim();
      double precio = Double.parseDouble(txtPrecioActualizar.getText().trim());
      boolean tiene5G = chk5gActualizar.isSelected();
      String estado = cmbActualizar.getSelectedItem().toString(); 
      int nit = Integer.parseInt(txtNitActualizar.getText().trim());
      
      ClaseA celActualizado = new ClaseA(imei, modelo, precio, tiene5G, estado, nit);
      
      boolean res = ServicioClaseA.actualizarCelular(celActualizado);
      
      if (res) {
          javax.swing.JOptionPane.showMessageDialog(this, "Celular actualizado correctamente.");
          
      } else {
          javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar celular.");
      }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarActionPerformed
    int imei = Integer.parseInt(txtImeiActualizar.getText().trim());

    ClaseA cel = ServicioClaseA.buscarCelular(imei);

    if(cel != null)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Celular encontrado");
    }
    else
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Celular NO encontrado");
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIActualizarCelular().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarActualizar;
    private javax.swing.JCheckBox chk5gActualizar;
    private javax.swing.JComboBox<String> cmbActualizar;
    private javax.swing.JLabel lblEstadoActualizar;
    private javax.swing.JLabel lblImeiActualizar;
    private javax.swing.JLabel lblModeloActualizar;
    private javax.swing.JLabel lblNitActualizar;
    private javax.swing.JLabel lblPrecioActualizar;
    private javax.swing.JLabel lblTiene5GActualizar;
    private javax.swing.JTextField txtImeiActualizar;
    private javax.swing.JTextField txtModeloActualizar;
    private javax.swing.JTextField txtNitActualizar;
    private javax.swing.JTextField txtPrecioActualizar;
    // End of variables declaration//GEN-END:variables
}
