/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectocelular.gui;

import com.mycompany.proyectocelular.modelo.ClaseA;
import com.mycompany.proyectocelular.modelo.Tienda;
import com.mycompany.proyectocelular.servicio.ServicioClaseA;
import com.mycompany.proyectocelular.servicio.ServicioTienda;

/**
 *
 * @author David Mahecha
 */
public class GUIActualizarTienda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIActualizarTienda.class.getName());

    /**
     * Creates new form GUIActualizarCelular
     */
    public GUIActualizarTienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNitActualizar = new javax.swing.JLabel();
        txtNitActualizar = new javax.swing.JTextField();
        lblNombreActualizar = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        lblEstadoActualizar = new javax.swing.JLabel();
        cmbActualizar = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnBuscarActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ActualizarCelular");

        lblNitActualizar.setText("NIT:");

        lblNombreActualizar.setText("NOMBRE:");

        lblEstadoActualizar.setText("Estado: ");

        cmbActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBuscarActualizar.setText("BUSCAR");
        btnBuscarActualizar.addActionListener(this::btnBuscarActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreActualizar)
                            .addComponent(lblNitActualizar)
                            .addComponent(lblEstadoActualizar))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNitActualizar)
                            .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnActualizar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNitActualizar)
                    .addComponent(txtNitActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActualizar)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoActualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBuscarActualizar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      int nit = Integer.parseInt(txtNitActualizar.getText().trim());
      String nombre = txtNombreActualizar.getText().trim();
      String estado = cmbActualizar.getSelectedItem().toString(); 

      
      Tienda tieActualizado = new Tienda(nit, nombre,  estado);
      
      boolean res = ServicioTienda.actualizarTienda(tieActualizado);
      
      if (res) {
          javax.swing.JOptionPane.showMessageDialog(this, "TIedna actualizado correctamente.");
          
      } else {
          javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar Tienda.");
      }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarActionPerformed
    int nit = Integer.parseInt(txtNitActualizar.getText().trim());

    Tienda tel = ServicioTienda.buscarTienda(nit);

    if(tel != null)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Tienda encontrado");
    }
    else
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Tienda NO encontrado");
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIActualizarTienda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarActualizar;
    private javax.swing.JComboBox<String> cmbActualizar;
    private javax.swing.JLabel lblEstadoActualizar;
    private javax.swing.JLabel lblNitActualizar;
    private javax.swing.JLabel lblNombreActualizar;
    private javax.swing.JTextField txtNitActualizar;
    private javax.swing.JTextField txtNombreActualizar;
    // End of variables declaration//GEN-END:variables
}
