/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectocelular.gui;

import java.io.FileNotFoundException;
import java.io.RandomAccessFile;

/**
 *
 * @author David Mahecha
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuTienda = new javax.swing.JMenu();
        menuAdiconarTienda = new javax.swing.JMenuItem();
        menuListarTienda = new javax.swing.JMenuItem();
        menuActualizarTienda = new javax.swing.JMenuItem();
        menuEliminarTienda = new javax.swing.JMenuItem();
        menuBuscarTienda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAdiconarCelular = new javax.swing.JMenuItem();
        menuListarCelulares = new javax.swing.JMenuItem();
        menuActualizarCelular = new javax.swing.JMenuItem();
        menuEliminarCelular = new javax.swing.JMenuItem();
        menuBuscarCelular = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDesarrolladores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setAutoRequestFocus(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Bienvenido al sistema de registro de celulares, aqui \nencontrará distintas opciones como: \nAdicionar la informacion de un celular.\nListar la informacion de todos los celulares guardados.\nActualizar la informacion de un celular en específico.\nEliminar toda la informacion de un celular.\n\nEstas opciones las encontrará en la parte superior de \nesta ventana en el icono \"Celular\". Seleccione la\nopcion que desee usar.");
        jScrollPane2.setViewportView(jTextArea2);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        menuTienda.setText("TIenda");

        menuAdiconarTienda.setText("Adicionar Tienda");
        menuAdiconarTienda.addActionListener(this::menuAdiconarTiendaActionPerformed);
        menuTienda.add(menuAdiconarTienda);

        menuListarTienda.setText("Listar Tienda");
        menuListarTienda.addActionListener(this::menuListarTiendaActionPerformed);
        menuTienda.add(menuListarTienda);

        menuActualizarTienda.setText("Actualizar Tienda");
        menuActualizarTienda.addActionListener(this::menuActualizarTiendaActionPerformed);
        menuTienda.add(menuActualizarTienda);

        menuEliminarTienda.setText("Eliminar Tienda");
        menuEliminarTienda.addActionListener(this::menuEliminarTiendaActionPerformed);
        menuTienda.add(menuEliminarTienda);

        menuBuscarTienda.setText("Buscar Tienda");
        menuBuscarTienda.addActionListener(this::menuBuscarTiendaActionPerformed);
        menuTienda.add(menuBuscarTienda);

        jMenuBar1.add(menuTienda);

        jMenu2.setText("Celular");

        menuAdiconarCelular.setText("Adicionar Celular");
        menuAdiconarCelular.addActionListener(this::menuAdiconarCelularActionPerformed);
        jMenu2.add(menuAdiconarCelular);

        menuListarCelulares.setText("Listar celulares");
        menuListarCelulares.addActionListener(this::menuListarCelularesActionPerformed);
        jMenu2.add(menuListarCelulares);

        menuActualizarCelular.setText("Actualizar celular");
        menuActualizarCelular.addActionListener(this::menuActualizarCelularActionPerformed);
        jMenu2.add(menuActualizarCelular);

        menuEliminarCelular.setText("Eliminar celular");
        menuEliminarCelular.addActionListener(this::menuEliminarCelularActionPerformed);
        jMenu2.add(menuEliminarCelular);

        menuBuscarCelular.setText("Buscar celular");
        menuBuscarCelular.addActionListener(this::menuBuscarCelularActionPerformed);
        jMenu2.add(menuBuscarCelular);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Acerca de...");

        menuDesarrolladores.setText("Desarrolladores");
        menuDesarrolladores.addActionListener(this::menuDesarrolladoresActionPerformed);
        jMenu3.add(menuDesarrolladores);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuListarCelularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarCelularesActionPerformed
       // MenuItem Listar
     GUIListarCelulares ventana = new GUIListarCelulares();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
    }//GEN-LAST:event_menuListarCelularesActionPerformed

    private void menuActualizarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarCelularActionPerformed
     GUIActualizarCelular ventana = new GUIActualizarCelular();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);// TODO add your handling code here:
    }//GEN-LAST:event_menuActualizarCelularActionPerformed

    private void menuEliminarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarCelularActionPerformed
     GUIEliminarCelular ventana = new GUIEliminarCelular();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);   // TODO add your handling code here:
    }//GEN-LAST:event_menuEliminarCelularActionPerformed

    private void menuBuscarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarCelularActionPerformed
     GUIBuscarCelular ventana = new GUIBuscarCelular();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);   // TODO add your handling code here:
    }//GEN-LAST:event_menuBuscarCelularActionPerformed

    private void menuAdiconarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdiconarCelularActionPerformed
     GUIAdicionarCelular ventana = new GUIAdicionarCelular();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);// TODO add your handling code here:
    }//GEN-LAST:event_menuAdiconarCelularActionPerformed

    private void menuDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesarrolladoresActionPerformed
     GUIDesarrolladores ventana = new GUIDesarrolladores();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
     // TODO add your handling code here:
    }//GEN-LAST:event_menuDesarrolladoresActionPerformed

    private void menuAdiconarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdiconarTiendaActionPerformed
     GUIAdicionarTienda ventana = new GUIAdicionarTienda();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
     // TODO add your handling code here:
    }//GEN-LAST:event_menuAdiconarTiendaActionPerformed

    private void menuListarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarTiendaActionPerformed
     GUIListarTienda ventana = new GUIListarTienda();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
     // TODO add your handling code here:
    }//GEN-LAST:event_menuListarTiendaActionPerformed

    private void menuActualizarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarTiendaActionPerformed
     GUIActualizarTienda ventana = new GUIActualizarTienda();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
     // TODO add your handling code here:
    }//GEN-LAST:event_menuActualizarTiendaActionPerformed

    private void menuEliminarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarTiendaActionPerformed
     GUIEliminarTienda ventana = new GUIEliminarTienda();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
     // TODO add your handling code here:
    }//GEN-LAST:event_menuEliminarTiendaActionPerformed

    private void menuBuscarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarTiendaActionPerformed
     GUIBuscarTienda ventana = new GUIBuscarTienda();
     ventana.setVisible(true);
     ventana.setLocationRelativeTo(this);
     // TODO add your handling code here:
    }//GEN-LAST:event_menuBuscarTiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenuItem menuActualizarCelular;
    private javax.swing.JMenuItem menuActualizarTienda;
    private javax.swing.JMenuItem menuAdiconarCelular;
    private javax.swing.JMenuItem menuAdiconarTienda;
    private javax.swing.JMenuItem menuBuscarCelular;
    private javax.swing.JMenuItem menuBuscarTienda;
    private javax.swing.JMenuItem menuDesarrolladores;
    private javax.swing.JMenuItem menuEliminarCelular;
    private javax.swing.JMenuItem menuEliminarTienda;
    private javax.swing.JMenuItem menuListarCelulares;
    private javax.swing.JMenuItem menuListarTienda;
    private javax.swing.JMenu menuTienda;
    // End of variables declaration//GEN-END:variables
}
